spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tsabitpoc?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: postgres
    password: admin
  sql:
    init:
      mode: never
  mail:
    host: csmtp.yaanimail.com
    port: 587
    username: ENC(uasjo+dPTdFlGS2bk9S4jjTJeFvD6K29E5fmFWdj3P8=)
    password: EgS7TOqB.
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: csmtp.yaanimail.com
  jpa:
    show-sql: false
  redis:
    host: localhost
    port: 6379

eureka:
  instance:
    prefer-ip-address: false
  server:
    host: localhost
    port: 9050
    username: ENC(f8tByks48wy5jecXO8GWtg==)
    password: ENC(dDorWPQjz8oCQzhwLTus8g==)

minio:
  host: localhost
  port: 9000
  access-key: 7Al0DVIghv9xSLtQ
  secret-key: r1H8eCUDggxAxtkeYG2gPYOqfltAfVyA
  bucket-name: sabit-turkcell-poc
  enabled: true

kafka:
  mock: true

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

integration:
  disable-ssl-hostnames:
    - apigwtst.turkcell.com.tr

storage:
  path: /Users/bkocoglu/Documents/projects/omreon/turkcell-sabit-poc/photos