spring:
  application:
    name: log-service
  cloud:
    stream:
      bindings:
        log-input-channel:  #TODO: change to correct destination
          destination: log
          binder: kafka-binder-poc
  kafka:
    consumer:
      auto-offset-reset: latest

server:
  port: 9059
  servlet:
    session:
      cookie:
        http-only: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://${eureka.server.username}:${eureka.server.password}@${eureka.server.host}:${eureka.server.port}/eureka/
    register-with-eureka: true
    fetch-registry: true

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator