spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/tsabitpoc?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: postgres
    password: admin
  sql:
    init:
      mode: never
  jpa:
    show-sql: false
  redis:
    host: localhost
    port: 6379

eureka:
  instance:
    prefer-ip-address: false
  server:
    host: localhost
    port: 9050
    username: user
    password: 12345

kafka:
  mock: true

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

