package com.atmosferpoc.core.model.type;

public enum ESchedulerTaskInfoName {
	API_GW_TOKEN_REFRESH,
	UPDATE_TRANSLATIONS,
	YAANI_MAIL_TOKEN_REFRESH,
	CHECK_AND_RESERVE_TOKEN_REFRESH,
	ACCOUNT_STATUS,
	EULA_STATUS_CHECK
}
