package com.atmosferpoc.core.model.type;

public enum IntegrationLogProcessType {
    LOGIN,
    ACCOUNT_CREATE,
    TRANSLATIONS_UPDATE,
    CREATE_SUBSCRIPTION,
    GET_ELIABLE,
    GET_TOKEN,
    CREATE_CUSTOMER,
    UPDATE_CUSTOMER,
    DELETE_CUSTOMER,
    UNSUBSCRIPTION,
    SUSPEND,
    VALIDATE_TOKEN,
    VALIDATE_SESSION,
    LOGOUT,
    LOGOUT_ALL,
    CREATE_DOMAIN,
    DELETE_DOMAIN,
    GET_DOMAIN_LIST,
    DNS_CHECK,
    CHECK_AND_RESERVE_HOSTNAME,
    DISTRIBUTION_LIST_CHECK
}