
spring:
  datasource:
    url: jdbc:postgresql://185.126.217.205:5432/postgres?useUnicode=true&autoReconnect=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: omreon
    password: root
  sql:
    init:
      mode: never
  jpa:
    show-sql: false


eureka:
  instance:
    prefer-ip-address: false
  server:
    host: localhost
    port: 9050
    username: ENC(f8tByks48wy5jecXO8GWtg==)
    password: ENC(dDorWPQjz8oCQzhwLTus8g==)

kafka:
  mock: true

task:
  schedule:
    account-status-cron: 0 5 0 * * *
    async-process-cron: '* */30 * * * ?'

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

integration:
  disable-ssl-hostnames:
    - adminpanel.yposta.net
    - testadminpanelapi.yposta.net
    - admin.yaani.local
    - partneradmin.yaani.local
    - apigwtst.turkcell.com.tr

encryption:
  enc-key: 8CA2ED7FE393CE9CA2BBABA446449C
