eureka:
  instance:
    prefer-ip-address: false
  server:
    host: localhost
    port: 9050
    username: ENC(f8tByks48wy5jecXO8GWtg==)
    password: ENC(dDorWPQjz8oCQzhwLTus8g==)

spring:
  datasource:
    url: jdbc:postgresql://185.126.217.205:5432/postgres?useUnicode=true&autoReconnect=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: omreon
    password: root
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - OPTIONS
              - PATCH
              - HEAD
    stream:
      binders:
        kafka-binder-poc:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers:
                        - 185.126.217.205:9092
  jpa:
    show-sql: false

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

