spring:
  application:
    name: advertisement-service
  datasource:
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      maximum-pool-size: 10
      connection-timeout: 50000
      idle-timeout: 900000
      max-lifetime: 2100000
    dbcp2:
      test-while-idle: true
      validationQuery: SELECT 1
      timeBetweenEvictionRunsMillis: 60000
    tomcat:
      max-wait: 15000
      max-active: 50
      test-on-borrow: true
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      connection.characterEncoding: utf-8
      connection.CharSet: utf-8
      connection.useUnicode: true
      hibernate.jdbc.time_zone: UTC
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
      enable_lazy_load_no_trans: true
      event:
        merge:
          entity_copy_observer: allow

server:
  port: 9052
  servlet:
    session:
      cookie:
        http-only: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://${eureka.server.username}:${eureka.server.password}@${eureka.server.host}:${eureka.server.port}/eureka/
    register-with-eureka: true
    fetch-registry: true

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
